/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import dao.ConnectionP;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.Date;

/**
 *
 * @author MARIEM
 */
public class AjouterUser extends javax.swing.JFrame {

    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String MobileNumberPattern = "^[0-9]*$";
    public int checkUsername = 0;

    /**
     * Creates new form AjouterUser
     */
    public AjouterUser() {
        initComponents();
        iconLabel.setVisible(false);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        ComboUserRole = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dateDob = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txtmobileNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtadress = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Ajouter Utilisateur");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 0, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, 850, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("User Role");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        ComboUserRole.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ComboUserRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Pharmacist" }));
        ComboUserRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboUserRoleActionPerformed(evt);
            }
        });
        getContentPane().add(ComboUserRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 280, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nom");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 50, -1));
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 280, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Date de Naissance");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));
        getContentPane().add(dateDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 270, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Numero Tel");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));
        getContentPane().add(txtmobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 260, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("E-mail");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 270, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Username");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, -1));

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 270, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 280, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Adresse");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, -1, -1));
        getContentPane().add(txtadress, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 290, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans-21\\Pharmacy Management System Images & Pattern\\save.png")); // NOI18N
        jButton1.setText("Enregistrer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, -1, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        iconLabel.setText("iconLabel");
        getContentPane().add(iconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans-21\\Pharmacy Management System Images & Pattern\\close.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 30, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
        String username = txtUserName.getText();
        if (!username.equals("")) {
            iconLabel.setVisible(true);
            iconLabel.setIcon(new ImageIcon("src\\images\\yes.png"));
            iconLabel.setText("");
            checkUsername = 0;

            try {
                Connection con = ConnectionP.getCon();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM appuser WHERE username = '" + username + "'");
                while (rs.next()) {
                    checkUsername = 1;
                    iconLabel.setIcon(new ImageIcon("src\\images\\no.png"));
                    iconLabel.setText("");

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);

            }
        } else {
            iconLabel.setVisible(false);

        }
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void ComboUserRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboUserRoleActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ComboUserRoleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtUserNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      /**  String userRole = (String) ComboUserRole.getSelectedItem();
       
        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = dateDob.getDate();
        String dob = "";
        if (date != null) {
            dob = dFormat.format(dateDob.getDate());

        }
        String mobileNumber = txtmobileNumber.getText();
        String email = txtemail.getText();
        String username = txtUserName.getText();
        String password = txtpassword.getText();
        String address = txtadress.getText();
         String name = txtname.getText();
        
        if (name.equals("")) {
            JOptionPane.showMessageDialog(null, "NAME FIELD IS REQUIERED .");
        } else if (dob.equals("")) {
            JOptionPane.showMessageDialog(null, "Date Naissance IS REQUIERED .");

        } else if (mobileNumber.equals("")) {
            JOptionPane.showMessageDialog(null, "MobileNumber IS REQUIERED .");
        } else if (!mobileNumber.matches(MobileNumberPattern) || mobileNumber.length() != 8) {
            JOptionPane.showMessageDialog(null, "MobileNumber filed is  invalid");
        } else if (email.equals("")) {
            JOptionPane.showMessageDialog(null, "email IS REQUIERED .");
        } else if (!email.matches(emailPattern)) {
            JOptionPane.showMessageDialog(null, "email filed is  invalid .");
        } else if (username.equals("")) {
            JOptionPane.showMessageDialog(null, "username  IS REQUIERED .");
        } else if (checkUsername == 1) {
            JOptionPane.showMessageDialog(null, "username exist");
        }
        else if (password.equals("")) {
            JOptionPane.showMessageDialog(null, "password IS REQUIERED .");}
        else if (address.equals("")) {
            JOptionPane.showMessageDialog(null, "address IS REQUIERED .");}
        else{
            try{
                    Connection con = ConnectionP.getCon();
            String query = "INSERT INTO appuser(userRole, name, dob, mobileNumber, email, username, password, adrress) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(query);
            
            pst.setString(1, "Admin");
            pst.setString(2, "Admin");
            pst.setString(3, "1990-10-04"); // Format de la date au format "année-mois-jour"
            pst.setString(4, "28469777");
            pst.setString(5, "admin@email.com");
            pst.setString(6, "admin");
            pst.setString(7, "admin");
            pst.setString(8, "Tunisia");
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "User ajouter avec succès");
             setVisible(false);
             new AjouterUser().setVisible(true);
             
            }catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                
            }
        }*/
      String userRole = (String) ComboUserRole.getSelectedItem();
       
SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
Date date = dateDob.getDate();
String dob = "";
if (date != null) {
    dob = dFormat.format(dateDob.getDate());
}
String mobileNumber = txtmobileNumber.getText();
String email = txtemail.getText();
String username = txtUserName.getText();
String password = txtpassword.getText();
String address = txtadress.getText();
String name = txtname.getText();
        
if (name.equals("")) {
    JOptionPane.showMessageDialog(null, "NAME FIELD IS REQUIRED.");
} else if (dob.equals("")) {
    JOptionPane.showMessageDialog(null, "Date Naissance IS REQUIRED.");
} else if (mobileNumber.equals("")) {
    JOptionPane.showMessageDialog(null, "MobileNumber IS REQUIRED.");
} else if (!mobileNumber.matches(MobileNumberPattern) || mobileNumber.length() != 8) {
    JOptionPane.showMessageDialog(null, "MobileNumber field is invalid.");
} else if (email.equals("")) {
    JOptionPane.showMessageDialog(null, "Email IS REQUIRED.");
} else if (!email.matches(emailPattern)) {
    JOptionPane.showMessageDialog(null, "Email field is invalid.");
} else if (username.equals("")) {
    JOptionPane.showMessageDialog(null, "Username IS REQUIRED.");
} else if (checkUsername == 1) {
    JOptionPane.showMessageDialog(null, "Username already exists.");
} else if (password.equals("")) {
    JOptionPane.showMessageDialog(null, "Password IS REQUIRED.");
} else if (address.equals("")) {
    JOptionPane.showMessageDialog(null, "Address IS REQUIRED.");
} else {
    try {
        Connection con = ConnectionP.getCon();
        String query = "INSERT INTO appuser(userRole, name, dob, mobileNumber, email, username, password, adrress) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement pst = con.prepareStatement(query);

        // Utiliser le rôle sélectionné dans la ComboBox
        pst.setString(1, userRole);
        pst.setString(2, name);
        pst.setString(3, dob);
        pst.setString(4, mobileNumber);
        pst.setString(5, email);
        pst.setString(6, username);
        pst.setString(7, password);
        pst.setString(8, address);

        pst.executeUpdate();
         
        JOptionPane.showMessageDialog(null, "User ajouté avec succès.");
         setVisible(false); // Ferme la fenêtre actuelle
      

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);}
    }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboUserRole;
    private com.toedter.calendar.JDateChooser dateDob;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtadress;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtmobileNumber;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpassword;
    // End of variables declaration//GEN-END:variables
}
