
import dao.ConnectionP;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MARIEM
 */
public class ConsulterCompany extends javax.swing.JFrame {

    /**
     * Creates new form ConsulterCompany
     */
    public ConsulterCompany() { 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Adresse", "CodeFiscale"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 910, 333));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Liste des Company");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 43, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 910, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("cliquer sur un ligne pour effacer company");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 448, 306, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\PHARMACIE SYSTEM MANAGMENT\\src\\images\\all_pages_background.png")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-390, -70, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
      try {
        Connection con = ConnectionP.getCon();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("select * from company");
        while (rs.next()) {
            model.addRow(new Object[]{rs.getString("idComp"), rs.getString("nom"), rs.getString("adresse"),rs.getString("codeFiscale")});
        }

       /* try{
            Connection con = ConnectionP.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from appuser");
            while(rs.next()){
               model.addRow(new Object[]{rs.getString("appuser_pk"), rs.getString("name"), rs.getString("userRole"), rs.getString("dob"), rs.getString("mobilenumber"), rs.getString("email"), rs.getString("username"), rs.getString("Password"), rs.getString("address")});
            }*/
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
           int index = jTable1.getSelectedRow();

        if (index != -1) {
            String id = jTable1.getValueAt(index, 0).toString();
            int choice = JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer cette entreprise ?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                try {
                    Connection con = ConnectionP.getCon();
                    PreparedStatement ps = con.prepareStatement("DELETE FROM company WHERE idComp=?");
                    ps.setString(1, id);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Entreprise supprimée avec succès");
                    // Rafraîchir la table après la suppression
                    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }}
    }//GEN-LAST:event_jTable1MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();

        if (index != -1) {
            String id = jTable1.getValueAt(index, 0).toString();
            int choice = JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer cette entreprise ?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                try {
                    Connection con = ConnectionP.getCon();
                    PreparedStatement ps = con.prepareStatement("DELETE FROM company WHERE idComp=?");
                    ps.setString(1, id);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Entreprise supprimée avec succès");
                    // Rafraîchir la table après la suppression
                   
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                
                 DefaultTableModel model = (DefaultTableModel) jTable1.getModel();}
        
      try {
        Connection con = ConnectionP.getCon();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("select * from company ");
        while (rs.next()) {
            model.addRow(new Object[]{ rs.getString("uniqueID"), rs.getString("name"), rs.getString("companyName"), rs.getString("quantity"), rs.getString("price")});
        }

       /* try{
            Connection con = ConnectionP.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from appuser");
            while(rs.next()){
               model.addRow(new Object[]{rs.getString("appuser_pk"), rs.getString("name"), rs.getString("userRole"), rs.getString("dob"), rs.getString("mobilenumber"), rs.getString("email"), rs.getString("username"), rs.getString("Password"), rs.getString("address")});
            }*/
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }                                   
            
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
         int index = jTable1.getSelectedRow();

        TableModel model = jTable1.getModel();
        String id = model.getValueAt(index, 0).toString();
        
       
            int choice = JOptionPane.showConfirmDialog(null, "Do you want to delete this medicament ?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                try {
                    Connection con = ConnectionP.getCon();
                    PreparedStatement ps = con.prepareStatement("DELETE FROM appuser WHERE medicine_pk=?");
                    ps.setString(1, id);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "medicament successfully deleted");
                   setVisible(false);
                    new ConsulterMedicament().setVisible(true);
                 
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            
    }//GEN-LAST:event_formMouseClicked
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsulterCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsulterCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsulterCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsulterCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsulterCompany().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
