
import dao.ConnectionP;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MARIEM
 */
public class UpdateMed extends javax.swing.JFrame {
      public String numberPattern ="^[0-9]*$";

    /**
     * Creates new form UpdateMed
     */
    public UpdateMed() {
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtuniqueId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtdepot = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrix = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtAddQT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Modifier Medicament");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 6, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, 873, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Medecine ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 78, 103, -1));

        txtuniqueId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtuniqueId, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 78, 291, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\PHARMACIE SYSTEM MANAGMENT\\src\\images\\search.png")); // NOI18N
        jButton1.setText("chercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 76, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 129, 76, -1));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\PHARMACIE SYSTEM MANAGMENT\\src\\images\\close.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 0, -1, -1));

        txtname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 157, 197, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Depot");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 215, 92, -1));

        txtdepot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtdepot, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 249, 197, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 297, 63, -1));

        txtQuantity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 331, 197, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Prix");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 129, 46, -1));

        txtPrix.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtPrix, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 157, 198, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\PHARMACIE SYSTEM MANAGMENT\\src\\images\\save.png")); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 205, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("ADD Quantity");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 384, -1, -1));

        txtAddQT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtAddQT, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 381, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      /**  int checkMedicamentExist = 0;
        String uniqueID = txtuniqueId.getText();
        if(uniqueID .equals("")){
            JOptionPane.showMessageDialog(null,"uniqueID filed is required");
            
        }else{
            
            try{
                Connection con = ConnectionP.getCon();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM medicine WHERE uniqueID  = '" + uniqueID  + "'");
                while (rs.next()) {
                    txtuniqueId.setEditable(false);
                   
                   txtname.setText("name");
                   txtdepot.setText("depot");
                    txtQuantity.setText(rs.getString("Quantity"));
                    txtPrix.setText(rs.getString("price"));
                    checkMedicamentExist = 1;
             
                 
                
         }
}               catch(Exception e){
                  JOptionPane.showMessageDialog(null, e);
                 }
                                
                        
                    
                   
         
                          
                  
                        
                    if(checkMedicamentExist == 0){
                JOptionPane.showMessageDialog(null,"Medicament n'existe pas");
                
            }
                    
        }  */       
                
        int checkMedicamentExist = 0;
    String uniqueID = txtuniqueId.getText();
    if(uniqueID.equals("")) {
        JOptionPane.showMessageDialog(null, "Le champ uniqueID est requis");
    } else {
        try {
            Connection con = ConnectionP.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM medicine WHERE uniqueID = '" + uniqueID + "'");
            while (rs.next()) {
                txtuniqueId.setEditable(false);
                txtname.setText(rs.getString("name")); // Afficher le nom du médicament
                txtdepot.setText(rs.getString("companyName"));
                txtQuantity.setText(rs.getString("Quantity"));
                txtPrix.setText(rs.getString("price"));
                checkMedicamentExist = 1;
            }
            if (checkMedicamentExist == 0) {
                JOptionPane.showMessageDialog(null, "Le médicament n'existe pas");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }        
           
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String uniqueID = txtuniqueId.getText();
    String name = txtname.getText();
    String companyName = txtdepot.getText();
    String quantity = txtQuantity.getText();
    String price = txtPrix.getText();
        String addQuantity = txtAddQT.getText();
        int totalQuantity = 0 ;
         if(addQuantity .equals("") ) {
       totalQuantity = Integer.parseInt(quantity);
    } else {
             totalQuantity = Integer.parseInt(quantity)+Integer.parseInt(addQuantity);
         }
        
    if(uniqueID.equals("") || name.equals("") || companyName.equals("") || quantity.equals("") || price.equals("")) {
        JOptionPane.showMessageDialog(null, "Tous les champs sont requis");
    } else {
        try {
            Connection con = ConnectionP.getCon();
            String query = "UPDATE medicine SET name=?, companyName=?, Quantity=?, price=? WHERE uniqueID=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, name);
            pst.setString(2, companyName);
            pst.setString(3, quantity);
            pst.setString(4, price);
            pst.setString(5, uniqueID);
            
            int updatedRows = pst.executeUpdate();
              if (updatedRows > 0) {
                JOptionPane.showMessageDialog(null, "Médicament mis à jour avec succès");
                // Vous pouvez ajouter d'autres actions si nécessaire
            } else {
                JOptionPane.showMessageDialog(null, "Échec de la mise à jour du médicament");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
       
    }                                        

    private void formComponentShown(java.awt.event.ComponentEvent evt) {                                    
        // TODO add your handling code here:
                                       

        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAddQT;
    private javax.swing.JTextField txtPrix;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtdepot;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtuniqueId;
    // End of variables declaration//GEN-END:variables
}
