
import dao.ConnectionP;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MARIEM
 */
public class UpdateComp extends javax.swing.JFrame {

    /**
     * Creates new form UpdateComp
     */
    public UpdateComp() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtIDCompany = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAdress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCodefiscale = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("UPDATE COMPANY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 22, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 78, 850, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ID Company");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 104, 95, -1));

        txtIDCompany.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtIDCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 101, 201, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\PHARMACIE SYSTEM MANAGMENT\\src\\images\\search.png")); // NOI18N
        jButton1.setText("Rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nom");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 191, 95, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 185, 201, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Adress");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 255, -1, -1));

        txtAdress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdressActionPerformed(evt);
            }
        });
        getContentPane().add(txtAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 255, 201, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("CodeFiscale");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 331, 95, -1));

        txtCodefiscale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtCodefiscale, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 325, 201, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\PHARMACIE SYSTEM MANAGMENT\\src\\images\\save.png")); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 410, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int checkMedicamentExist = 0;
    String uniqueID = txtIDCompany.getText();
    if(uniqueID.equals("")) {
        JOptionPane.showMessageDialog(null, "Le champ uniqueID est requis");
    } else {
        try {
            Connection con = ConnectionP.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM company WHERE idComp = '" + uniqueID + "'");
            while (rs.next()) {
                txtIDCompany.setEditable(false);
               txtName.setText(rs.getString("nom")); // Afficher le nom du médicament
                txtAdress.setText(rs.getString("adresse"));
              
                txtCodefiscale.setText(rs.getString("codeFiscale"));
                checkMedicamentExist = 1;
            }
            if (checkMedicamentExist == 0) {
                JOptionPane.showMessageDialog(null, "Company  n'existe pas");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
}
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdressActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String idComp =  txtIDCompany.getText();
        String nom = txtName.getText();
        String adress = txtAdress.getText();
        String codefiscale = txtCodefiscale.getText();

        if(idComp.equals("") || nom.equals("") || adress.equals("") || codefiscale.equals("")) {
            JOptionPane.showMessageDialog(null, "Tous les champs sont requis");
        } else {
            try {
                Connection con = ConnectionP.getCon();
                String query = "UPDATE company SET companyName=?, companyAdress=?, companyCodefiscale=? WHERE idComp=?";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, nom);
                pst.setString(2, adress);
                pst.setString(3, codefiscale);
                pst.setString(4, idComp);

                int updatedRows = pst.executeUpdate();
                if (updatedRows > 0) {
                    JOptionPane.showMessageDialog(null, "Entreprise mise à jour avec succès");
                } else {
                    JOptionPane.showMessageDialog(null, "Échec de la mise à jour de l'entreprise");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateComp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtCodefiscale;
    private javax.swing.JTextField txtIDCompany;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
